# Generated by Django 6.0.1 on 2026-02-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
    ]
