# Generated by Django 6.0.1 on 2026-04-09 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20260219_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('phone', models.CharField(max_length=20, verbose_name='電話番号')),
                ('car_model', models.CharField(max_length=100, verbose_name='車種名')),
                ('car_color', models.CharField(blank=True, max_length=100, null=True, verbose_name='年式/色')),
                ('message', models.TextField(verbose_name='ご相談内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='送信日時')),
            ],
            options={
                'verbose_name': 'お問い合わせ',
                'verbose_name_plural': 'お問い合わせ一覧',
            },
        ),
    ]
